<?php
function printsPage(){
	$CI =& get_instance();
	$CI->make->sDivRow();
		$CI->make->sDivCol();
			$CI->make->sBox('primary');
				$CI->make->sBoxHead();
					$CI->make->boxTitle('Search');
				$CI->make->eBoxHead();
				$CI->make->sBoxBody();
					$CI->make->sForm("reprint/results",array('id'=>'search-form'));
						$CI->make->sDivRow();
							$CI->make->sDivCol(4);
								$CI->make->input('Reference No.','receipt',null,'Search Receipt No. or Order No.',array('class'=>'rOkay'));
							$CI->make->eDivCol();
							$CI->make->sDivCol(2);
								$CI->make->button(fa('fa-search').' Submit',array('style'=>'margin-top:24px;','id'=>'search-btn'),'primary');
							$CI->make->eDivCol();
						$CI->make->eDivRow();
					$CI->make->eForm();
				$CI->make->eBoxBody();
			$CI->make->eBox();
		$CI->make->eDivCol();
	$CI->make->eDivRow();
	$CI->make->sDivRow();
		$CI->make->sDivCol(4);
			$CI->make->sBox('default',array('class'=>'box-solid'));
				$CI->make->sBoxHead();
					$CI->make->boxTitle(fa('fa-list').' Search Results');
				$CI->make->eBoxHead();
				$CI->make->sBoxBody();
					$CI->make->sDiv(array('id'=>'results-div'));
					$CI->make->eDiv();
				$CI->make->eBoxBody();
			$CI->make->eBox();
		$CI->make->eDivCol();
		$CI->make->sDivCol(8);
			$CI->make->sBox('default',array('class'=>'box-solid'));
				$CI->make->sBoxHead();
					$CI->make->button(fa('fa-print').' Print',array('id'=>'print-btn','class'=>'pull-right','style'=>'margin-top:10px;margin-right:10px;margin-bottom:10px;'),'success');
				$CI->make->eBoxHead();
				$CI->make->sBoxBody(array('class'=>'bg-gray','style'=>'min-height:50px;'));
					$CI->make->sDiv(array('id'=>'print-div','style'=>'margin:0 auto;position:relative;width:310px;'));
					$CI->make->eDiv();
				$CI->make->eBoxBody();
			$CI->make->eBox();
		$CI->make->eDivCol();
	$CI->make->eDivRow();
	return $CI->make->code();
}

function printAllPage(){
	$CI =& get_instance();
	$CI->make->sDivRow();
		$CI->make->sDivCol();
			$CI->make->sBox('primary');
				$CI->make->sBoxBody();
					$CI->make->sForm("reprint/resultsAll",array('id'=>'search-form'));
					$CI->make->sDivRow();
						$CI->make->sDivCol(4);
							$CI->make->input('Date & Time Range','calendar_range',null,null,array('class'=>'rOkay daterangepicker','style'=>'position:initial;'),fa('fa-calendar'));
						$CI->make->eDivCol();
						$CI->make->sDivCol(4);
							$CI->make->button(fa('fa-refresh').' Generate',array('id'=>'gen-rep','style'=>'margin-top:24px;margin-right:10px;'),'primary');
							// $CI->make->button(fa('fa-file-excel-o').' Generate as Excel',array('id'=>'excel-btn','style'=>'margin-top:24px;'),'success');
						$CI->make->eDivCol();
                	$CI->make->eDivRow();
                	$CI->make->eForm();
				$CI->make->eBoxBody();
			$CI->make->eBox();
		$CI->make->eDivCol();
	$CI->make->eDivRow();
	$CI->make->sDivRow();
		// $CI->make->sDivCol(4);
		// 	$CI->make->sBox('default',array('class'=>'box-solid'));
		// 		$CI->make->sBoxHead();
		// 			$CI->make->boxTitle(fa('fa-list').' Search Results');
		// 		$CI->make->eBoxHead();
		// 		$CI->make->sBoxBody();
		// 			$CI->make->sDiv(array('id'=>'results-div'));
		// 			$CI->make->eDiv();
		// 		$CI->make->eBoxBody();
		// 	$CI->make->eBox();
		// $CI->make->eDivCol();
		$CI->make->sDivCol(12);
			$CI->make->sBox('default',array('class'=>'box-solid'));
				$CI->make->sBoxHead();
					$CI->make->button(fa('fa-print').' Save',array('id'=>'print-btn','class'=>'pull-right','style'=>'margin-top:10px;margin-right:10px;margin-bottom:10px;'),'success');
				$CI->make->eBoxHead();
				$CI->make->sBoxBody(array('class'=>'bg-gray','style'=>'min-height:50px;'));
					$CI->make->sDiv(array('id'=>'print-div','style'=>'margin:0 auto;position:relative;width:300px;'));
					$CI->make->eDiv();
				$CI->make->eBoxBody();
			$CI->make->eBox();
		$CI->make->eDivCol();
	$CI->make->eDivRow();

	return $CI->make->code();
}

function printsPage2(){
	$CI =& get_instance();
	$CI->make->sDivRow();
		$CI->make->sDivCol();
			$CI->make->sBox('primary');
				$CI->make->sBoxHead();
					$CI->make->boxTitle('Search');
				$CI->make->eBoxHead();
				$CI->make->sBoxBody();
					$CI->make->sForm("reprint/results_reprint",array('id'=>'search-form'));
						$CI->make->sDivRow();
							$CI->make->sDivCol(4);
								// $CI->make->input('Reference No.','receipt',null,'Search Receipt No. or Order No.',array('class'=>'rOkay'));
								$CI->make->input('Date & Time Range','calendar_range',null,null,array('class'=>'rOkay daterangepicker','style'=>'position:initial;'),fa('fa-calendar'));
							$CI->make->eDivCol();
							$CI->make->sDivCol(4);
								$CI->make->paymentModeDrop('Payment Type','payment_type',null,'All',array("id"=>"payment_type", 'class'=>''));
							$CI->make->eDivCol();
							$CI->make->sDivCol(2);
								$CI->make->button(fa('fa-search').' Submit',array('style'=>'margin-top:24px;','id'=>'search-btn'),'primary');
							$CI->make->eDivCol();
						$CI->make->eDivRow();
					$CI->make->eForm();
				$CI->make->eBoxBody();
			$CI->make->eBox();
		$CI->make->eDivCol();
	$CI->make->eDivRow();
	$CI->make->sDivRow();
		$CI->make->sDivCol(4);
			$CI->make->sBox('default',array('class'=>'box-solid'));
				$CI->make->sBoxHead();
					$CI->make->boxTitle(fa('fa-list').' Search Results');
				$CI->make->eBoxHead();
				$CI->make->sBoxBody();
					$CI->make->sDiv(array('id'=>'results-div'));
					$CI->make->eDiv();
				$CI->make->eBoxBody();
			$CI->make->eBox();
		$CI->make->eDivCol();
		$CI->make->sDivCol(8);
			$CI->make->sBox('default',array('class'=>'box-solid'));
				$CI->make->sBoxHead();
					$CI->make->button(fa('fa-print').' Print',array('id'=>'print-btn','class'=>'pull-right','style'=>'margin-top:10px;margin-right:10px;margin-bottom:10px;'),'success');
				$CI->make->eBoxHead();
				$CI->make->sBoxBody(array('class'=>'bg-gray','style'=>'min-height:50px;'));
					$CI->make->sDiv(array('id'=>'print-div','style'=>'margin:0 auto;position:relative;width:310px;'));
					$CI->make->eDiv();
				$CI->make->eBoxBody();
			$CI->make->eBox();
		$CI->make->eDivCol();
	$CI->make->eDivRow();
	return $CI->make->code();
}
function makeViewform($sales_id){
	$CI =& get_instance();
	$CI->make->sDivRow();
		$CI->make->sDivCol(12);
			// $CI->make->sBoxHead();
			// 	$CI->make->button(fa('fa-print').' Print',array('id'=>'print-btn-paid','class'=>'pull-right','style'=>'margin-top:10px;margin-right:10px;margin-bottom:10px;'),'success');

			// 	$CI->make->button(fa('fa-envelope').' Email',array('id'=>'print-btn-email','class'=>'pull-right','style'=>'margin-top:10px;margin-right:10px;margin-bottom:10px;'),'success');
			// $CI->make->eBoxHead();
		$CI->make->eDivCol();
		$CI->make->sDivCol(12);
			$CI->make->sBox('default',array('class'=>'box-solid'));
				// $CI->make->sBoxHead();
				// 	$CI->make->button(fa('fa-print').' Print',array('id'=>'print-btn','class'=>'pull-right','style'=>'margin-top:10px;margin-right:10px;margin-bottom:10px;'),'success');
				// $CI->make->eBoxHead();
				$CI->make->hidden('sales_id',$sales_id);
				$CI->make->sBoxBody(array('class'=>'bg-gray','style'=>'min-height:50px;'));
					$CI->make->sDiv(array('id'=>'print-div','style'=>'margin:0 auto;position:relative;width:310px;'));
					$CI->make->eDiv();
				$CI->make->eBoxBody();
			$CI->make->eBox();
		$CI->make->eDivCol();
	$CI->make->eDivRow();
	return $CI->make->code();
}
?>