TRUNCATE `cashout_details`;
TRUNCATE `cashout_entries`;
TRUNCATE `ci_sessions`;
TRUNCATE `item_moves`;
TRUNCATE `logs`;
TRUNCATE `read_details`;
TRUNCATE `reasons`;
TRUNCATE `rob_files`;
TRUNCATE `shift_entries`;
TRUNCATE `shifts`;
TRUNCATE `trans_adjustment_details`;
TRUNCATE `trans_adjustments`;
TRUNCATE `trans_receiving_details`;
TRUNCATE `trans_receivings`;
TRUNCATE `trans_spoilage_details`;
TRUNCATE `trans_spoilage`;
TRUNCATE `trans_voids`;
TRUNCATE `trans_refs`;
TRUNCATE `trans_sales`;
TRUNCATE `trans_sales_charges`;
TRUNCATE `trans_sales_discounts`;
TRUNCATE `trans_sales_items`;
TRUNCATE `trans_sales_menu_modifiers`;
TRUNCATE `trans_sales_menus`;
TRUNCATE `trans_sales_no_tax`;
TRUNCATE `trans_sales_payments`;
TRUNCATE `trans_sales_tax`;
TRUNCATE `trans_sales_zero_rated`;
TRUNCATE `trans_sales_local_tax`;
TRUNCATE `trans_sales_loyalty_points`;
TRUNCATE `ortigas_read_details`;
TRUNCATE `customers_bank`;
TRUNCATE `sync_logs`;
TRUNCATE `master_logs`;
TRUNCATE `tables`;
TRUNCATE `coupons`;
TRUNCATE `trans_receiving_menu`;
TRUNCATE `trans_receiving_menu_details`;
TRUNCATE `menu_moves`;
TRUNCATE `users`;
TRUNCATE `receipt_discounts`;


UPDATE trans_types set next_ref = '00000001' WHERE type_id = 10;
UPDATE trans_types set next_ref = 'R000001' WHERE type_id = 20;
UPDATE trans_types set next_ref = 'A000001' WHERE type_id = 30;
UPDATE trans_types set next_ref = 'V000001' WHERE type_id = 11;
UPDATE trans_types set next_ref = 'C000001' WHERE type_id = 40;
UPDATE trans_types set next_ref = 'S000001' WHERE type_id = 35;
UPDATE trans_types set next_ref = 'RM000001' WHERE type_id = 55;


UPDATE users set sync_id  = NULL ;
UPDATE users set master_id  = NULL ;
UPDATE menus set master_id  = NULL ;
UPDATE menu_categories set master_id  = NULL ;
UPDATE menu_subcategories set master_id  = NULL;
UPDATE items set master_id  = NULL ;
UPDATE categories set master_id  = NULL;
UPDATE subcategories set master_id  = NULL ;
UPDATE suppliers set master_id  = NULL ;
UPDATE locations set master_id  = NULL ;
UPDATE terminals set master_id  = NULL ;
UPDATE menu_recipe set master_id  = NULL ;
UPDATE modifiers set master_id  = NULL ;
UPDATE modifier_groups set master_id  = NULL ;
UPDATE modifier_group_details set master_id  = NULL ;