TRUNCATE `cashout_details`;
TRUNCATE `cashout_entries`;
TRUNCATE `ci_sessions`;
TRUNCATE `item_moves`;
TRUNCATE `menu_moves`;
TRUNCATE `logs`;
TRUNCATE `read_details`;
TRUNCATE `reasons`;
TRUNCATE `rob_files`;
TRUNCATE `shift_entries`;
TRUNCATE `shifts`;
TRUNCATE `trans_adjustment_details`;
TRUNCATE `trans_adjustments`;
TRUNCATE `trans_receiving_details`;
TRUNCATE `trans_receivings`;
TRUNCATE `trans_spoilage_details`;
TRUNCATE `trans_spoilage`;
TRUNCATE `trans_voids`;
TRUNCATE `trans_refs`;
TRUNCATE `trans_sales`;
TRUNCATE `trans_sales_charges`;
TRUNCATE `trans_sales_discounts`;
TRUNCATE `trans_sales_items`;
TRUNCATE `trans_sales_menu_modifiers`;
TRUNCATE `trans_sales_menus`;
TRUNCATE `trans_sales_no_tax`;
TRUNCATE `trans_sales_payments`;
TRUNCATE `trans_sales_tax`;
TRUNCATE `trans_sales_zero_rated`;
TRUNCATE `trans_sales_local_tax`;
TRUNCATE `trans_sales_loyalty_points`;
TRUNCATE `ortigas_read_details`;
TRUNCATE `customers_bank`;
TRUNCATE `master_logs`;
TRUNCATE `tables`;
TRUNCATE `coupons`;
TRUNCATE `menus`;
TRUNCATE `menu_subcategories`;
TRUNCATE `users`;


UPDATE trans_types set next_ref = '00000001' WHERE type_id = 10;
UPDATE trans_types set next_ref = 'R000001' WHERE type_id = 20;
UPDATE trans_types set next_ref = 'A000001' WHERE type_id = 30;
UPDATE trans_types set next_ref = 'V000001' WHERE type_id = 11;
UPDATE trans_types set next_ref = 'C000001' WHERE type_id = 40;
UPDATE trans_types set next_ref = 'S000001' WHERE type_id = 35;
